import React from "react";

const dataDB = React.useMemo(
  () => [
    {
      myvalue: "DEV",
      mysubject: "DataFlow",
      purpose: "Создать приложение для сбора данных",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "DEV",
      mysubject: "Видеокурсы",
      purpose: "",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "DEV",
      mysubject: "NiceDay",
      purpose: "",
      task:
        "Создать приложение, которое показывает красивые даты типа 01.01.21",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "DEV",
      mysubject: "Школа Юнити",
      purpose: "Привлечение учеников в школу",
      task: "Опредлить платформу",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "DEV",
      mysubject: "10resume",
      purpose: "Иметь отличное портфолио",
      task: "Доработать",
      act: "Сделать страницу Tech",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "DEV",
      mysubject: "DataFlow",
      purpose: "",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "DEV",
      mysubject: "Mindmaps",
      purpose: "Представлять проповедь в визуальной карте",
      task: "Найти подходящую библиотеку",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "FIT",
      mysubject: "Зубы",
      purpose: "Иметь здровые зубы",
      task: "Вылечить 24 зуб и парадонтит",
      act: "Отпроситься на прием 18.02.21",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "FIT",
      mysubject: "Подставка для работы стоя",
      purpose: "Обеспечить ежедневную подвижность",
      task: "Разработать технический проект подставки",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "FIT",
      mysubject: "Чай",
      purpose: "Пить чай на рабочем месте",
      task: "Принести пачку",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Fit",
      mysubject: "Браслет",
      purpose: "Контроль пульса и",
      task: "Зарядить часы",
      act: "Найти зарядку",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Fit",
      mysubject: "н.теннис",
      purpose: "",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "SKILLS",
      mysubject: "Нумерованный",
      purpose: "",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "SKILLS",
      mysubject: "SpeakPeak",
      purpose: "Научиться бегло говорить",
      task: "Регулярно практиковаться",
      act: "Подготовить фразы для разговора",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "TECH",
      mysubject: "HDD 3Tb",
      purpose: "Использовать диск под долгосрочное хранение",
      task: "Найти и проверить диск на ошибки",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "TECH",
      mysubject: "Закладки сайтов",
      purpose: "Создать систему наглядного хранения закладок",
      task: "Плагин Diilo - разобраться",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "TECH",
      mysubject: "ZALMAN",
      purpose: "Иметь полный набор технического ПО",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Мышление",
      mysubject: "Сумка для бумаг",
      purpose: "Всега иметь записи в быстром доступе",
      task: "Выбрать подходящую сумку",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Мышление",
      mysubject: "Уголки",
      purpose: "Поддерживать записи в организованном состоянии",
      task: "Купить в магазине",
      act: "Найти магазин где продаются",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Мышление",
      mysubject: "Закладки",
      purpose: "Наглядный поиск и фильтрация",
      task: "Найти сервис или плагин",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Мышление",
      mysubject: "GoogleDrive",
      purpose: "Обеспечить поиск по ценным книгам",
      task: "Навести порядок на диске",
      act: "Удалить лишние книги",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Мышление",
      mysubject: "Цели 2021",
      purpose: "Достичь поставленных целей",
      task: "Держать в фокусе внимания",
      act: "Ежедневно просматривать",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Обучение",
      mysubject: "Telegram",
      purpose: "Развивать навык разработчика",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Работа",
      mysubject: "Вакансии",
      purpose: "Трудоустроиться в хорошую компанию",
      task: "Составить список хороших компаний",
      act: "Просматривать вакансии",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Работа",
      mysubject: "ПК для отчетности",
      purpose: "Создать рабочее место в кабинете Обидиной",
      task: "Получить ПК для подготовки",
      act: "Ждать",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Работа",
      mysubject: "nziv.ru",
      purpose: "Акуализировать данные в контактах",
      task: "Сменить Варламову на Васильеву",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Работа",
      mysubject: "hotel.nziv.ru",
      purpose: "",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Работа",
      mysubject: "ЭЦП на Воропаева",
      purpose: "Получить ЭЦП для работы",
      task: "Получить сканы заявления и доверенности",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Работа",
      mysubject: "Квиток",
      purpose: "Требуется получить квиток под роспись",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Работа",
      mysubject: "USB Консультант",
      purpose: "Предоставить Грушевой",
      task: "Получить у доставки",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Работа",
      mysubject: "nziv.local",
      purpose: "Вернуть расписание столовой",
      task: "Выложить расписание",
      act: "Сверстать. Файл в библиотеке изображ-й",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Работа",
      mysubject: "Серкова",
      purpose: "Настроить отчетность в РосАккредитацию",
      task: "Купить ключ для VipNet и ЭЦП",
      act: "Получить договор и отдать на оформление. Дождаться оплаты счета.",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Работа",
      mysubject: "hotel.nziv.ru",
      purpose: "Сделать сайт для гостиницы",
      task: "Наполнить данные",
      act: "Страницы по количеству коек",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Работа",
      mysubject: "Скуд",
      purpose: "",
      task: "Посмотреть как реализовано",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Работа",
      mysubject: "Уваров",
      purpose: "Определить дальнейшее использование",
      task: "Выяснить необходимость",
      act: "Спросить у Воронина",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Работа",
      mysubject: "Казначейство",
      purpose: "Сбербанк и Новиком. Токены на Бахарева и Аникееву",
      task: "Настроить.",
      act: "Ждем подписания заявлений для активации сертификатов ЕКК",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Работа",
      mysubject: "ЭЦП на Смирнова",
      purpose: "Продлить работу с ЭЦП",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Семья",
      mysubject: "Квартира",
      purpose:
        "Обновить жилье, чтобы иметь комфортные условия и чтобы повысить привлекательность и стоимость жилья",
      task: "Провести оценку стоимости и необходимости ремонта",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Семья",
      mysubject: "Надюшка",
      purpose: "Направить мышление на развитие",
      task: "Проработать ценности и цели",
      act: "Запланировать разговор",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Семья",
      mysubject: "Финансы",
      purpose: "Сохранить и умножить сбережения",
      task: "Купить доходные акции",
      act: "Найти сайт с рейтингом инвесторов",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Семья",
      mysubject: "Земля в Пайвино",
      purpose: "Получить финансы от продажи земли",
      task: "Выставить землю на продажу",
      act: "Узнать точный адрес",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Семья",
      mysubject: "Лампочки",
      purpose: "Иметь хорошее освещение в квартире",
      task: "Купить лампочки по акции",
      act: "Сходить в ГалаМаркт",
      issue: "до 16 числа",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Семья",
      mysubject: "Надюшка",
      purpose: "Помочь найти свое дело",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Семья",
      mysubject: "Родословная",
      purpose: "Иметь подробную картину семейной родостловной",
      task: "Собрать доступные данные",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Семья",
      mysubject: "Хостинг Алены",
      purpose: "Иметь оплаченные услуги",
      task: "Определить за что требуется оплата?",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Семья",
      mysubject: "500 р",
      purpose: "Получить доход на мегафон",
      task: "Использовать кредитную карту на 500 р.",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Семья",
      mysubject: "Кирилл",
      purpose: "Закончить обучение к колледже",
      task: "Добиться сдачи задания по сессии",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Церковные объявления",
      purpose: "Держать церковь в курсе событий и планов",
      task: "Составить список актуальных объявлений",
      act: "Подумать о необходимых объявлениях и записать их",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Суворова А.А.",
      purpose: "Привести образ жизни в достойный вид",
      task: "Сделать уборку в комнате",
      act: "Собрать добровольцев",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Червякова Р.В.",
      purpose: "Подготовить к крещению",
      task: "Побудить присоединиться к группе",
      act: "Встретиться и поговорить",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: 'Банер "Жизнь с Богом',
      purpose: "Наглядно представить Евангелие на Основах веры",
      task: "Найти и повесить банер в классе",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Пожилые члены",
      purpose: "Поспособствовать присутствию на собрании",
      task: "Решить на братском совете",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Теннисные мячи",
      purpose: "",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Основной Микрофон",
      purpose: "Восстановить работу микрофона",
      task: "Проверить кабель",
      act: "Провести диагностику",
      issue: "17.02.2021",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Червяков В.И.",
      purpose: "Научить презентации проповеди",
      task: "Провести тренировки",
      act: "Договориться о встрече",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Проповедь на Быт.1,1-24",
      purpose: "",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Двор ДМ",
      purpose: "Комфортное место для церковных общений",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Лапин К.В.",
      purpose: "Объяснить Евангелие",
      task: "Ответить на вопрос - Почему Бог допустил грехопадение?",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Список членов",
      purpose: "Иметь актуальные данные",
      task: "Уточнить на членском",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Суворова А.А.",
      purpose: "Обеспечить возможность слушать аудио",
      task: "Выбрать техническое решение",
      act: "Зайти в ДНС для консультации",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Основы веры",
      purpose: "Подготовить к крещению",
      task: "Написать программу курса",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Хостинг объединения",
      purpose: "Продлить аренду хостинга сайта объединения",
      task: "Оплатить на год",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Мёд",
      purpose: "Рассчитаться с Волжанкиным за мед",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Общее братское",
      purpose: "Развивать служение",
      task: "Подготовить вопросы",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Проповедь",
      purpose: "Подготовить проработанную проповедь с визуальной презентацией",
      task: "Богословский анализ важных тем",
      act: "Чтение систематики",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Финансы",
      purpose: "Разумно использовать финансы",
      task: "Продумать бюджет 2021",
      act: "Составить список расходов",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Зеркало",
      purpose:
        "Дать посетителям возможность проверить свой внешний вид, и украсить фое",
      task: "Повесить зеркало",
      act: "Согласовать с советом.",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Служение",
      purpose: "Сделать служение согласованным",
      task: "Составить список вопросов к совету",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Двор ДМ",
      purpose: "Сделать двор социальной точной притяжения",
      task: "Сделать презентацию для общего братского",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Членское",
      purpose: "Подготовить вопросы",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "Видеонаблюд.",
      purpose: "Держать территорию ДМ под наблюдением",
      task: "Настроить всем желающим",
      act: "Установить Спицину на ПК",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: "График проповедников",
      purpose: "Чтобы успеть подготовиться к проповеди",
      task: "",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "Служение",
      mysubject: 'Курс "Основы веры',
      purpose: "Подготовить программу подготовки к крещению",
      task: "Написать структуру программы курса",
      act: "",
      issue: "",
      variant: "",
      progress: "",
    },
    {
      myvalue: "DEV",
      mysubject: "10resume",
      purpose: "Найти удаленную работу",
      task: "Выложить в интернет",
      act: "Доделать",
      issue: "",
      variant: "",
      progress: "",
    },
  ],
  []
);

export default dataDB;
